# Required by J_GL (SPI display + I2C touch controller + GPIO DC pin)
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_GPIO=y

# Required by J_GL internals
CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
